apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-task
spec:
  steps:
    - name: deploy
      image: 'openshift/cli'
      script: |
        #!/bin/bash
        set -e
        oc apply -f deployment-config.yaml
        oc apply -f service-route.yaml
