apiVersion: tekton.dev/v1beta1
kind: PipelineResource
metadata:
  name: image-repo
spec:
  type: image
  params:
    - name: url
      value: 'image-registry.openshift-image-registry.svc:5000/wanthanai-dev/nodejs-app'
