apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: nodejs-pipeline
spec:
  tasks:
    - name: build
      taskRef:
        name: buildah
      resources:
        inputs:
          - name: source
            resourceRef:
              name: git-repo
        outputs:
          - name: image
            resourceRef:
              name: image-repo
      params:
        - name: image
          value: $(resources.outputs.image.url)
        - name: context
          value: /workspace/source
