apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: nodejs-pipeline-run
spec:
  pipelineRef:
    name: nodejs-pipeline
  resources:
    inputs:
      - name: source
        resourceRef:
          name: git-repo
    outputs:
      - name: image
        resourceRef:
          name: image-repo
