apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: nodejs-pipeline-run
spec:
  pipelineRef:
    name: nodejs-pipeline
  params:
  - name: git-url
    value: https://github.com/wanthanai/nodejs_openshit.git
  - name: git-revision
    value: dev
  - name: image
    value: docker.io/wanthanai/my-nodejs-app:latest
  - name: chart-path
    value: ./nodejs-chart
  - name: namespace
    value: wanthanai-dev
  workspaces:
  - name: shared-workspace
    emptyDir: {}
