apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: push-task
spec:
  params:
  - name: IMAGE
    description: The image name and tag to push
    type: string
  workspaces:
  - name: shared-workspace
  steps:
  - name: push
    image: gcr.io/kaniko-project/executor:latest
    script: |
      #!/bin/sh
      /kaniko/executor --context /workspace/shared-workspace --dockerfile /workspace/shared-workspace/Dockerfile --destination $(params.IMAGE)
