apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-task
spec:
  steps:
    - name: deploy
      image: quay.io/openshift/origin-cli:latest
      script: |
        oc apply -f deploy.yaml
