apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah
spec:
  steps:
    - name: build
      image: quay.io/buildah/stable:latest
      script: |
        buildah bud -f /workspace/source/Dockerfile -t $(params.image) /workspace/source
  params:
    - name: image
      description: Name of the image to build
      type: string
    - name: context
      description: Build context
      type: string
