apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: test-task
spec:
  steps:
    - name: test
      image: 'node:14'
      script: |
        #!/bin/bash
        set -e
        npm install
        npm test
