apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tekton-pipelines-role-binding
  namespace: wanthanai-dev
roleRef:
  kind: Role
  name: tekton-pipelines-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: wanthanai
  apiGroup: rbac.authorization.k8s.io

