apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: example
  namespace: wanthanai-dev
rules:
  - apiGroups: [""]
    resources: ["namespaces", "services", "pods"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["tekton.dev"]
    resources: ["pipelines", "pipelineruns", "pipelineascode", "pipelinecrds"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
