apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: nodejs-app
spec:
  replicas: 1
  selector:
    app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: 'image-registry.openshift-image-registry.svc:5000/wanthanai-dev/nodejs-app:latest'  # Replace 'your-project' with your actual project name
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - nodejs-app
        from:
          kind: ImageStreamTag
          name: 'nodejs-app:latest'
